const mongoose = require("mongoose");
const dotenv = require("dotenv");
const Product = require("./models/Product");
const User = require("./models/User");

dotenv.config();

const users = [
  {
    fullname: "Admin User",
    email: "admin@king.com",
    password: "admin123",
    role: "admin",
  },
  {
    fullname: "John Doe",
    email: "john@example.com",
    password: "john123",
    role: "user",
  },
];

const products = [
  {
    title: "Classic White Oxford Shirt",
    description: "A timeless white Oxford shirt crafted from premium cotton. Perfect for both casual and formal occasions with a tailored fit.",
    price: 89.99,
    discount: 10,
    category: "shirts",
    gender: "men",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Light Blue"],
    stock: 50,
    images: ["/uploads/product-1.jpg"],
    featured: true,
    rating: 4.5,
    numReviews: 12,
    reviews: [],
  },
  {
    title: "Slim Fit Dark Wash Jeans",
    description: "Premium dark wash denim jeans with a modern slim fit. Stretch fabric for all-day comfort.",
    price: 119.99,
    discount: 0,
    category: "jeans",
    gender: "men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Dark Blue", "Black"],
    stock: 35,
    images: ["/uploads/product-2.jpg"],
    featured: true,
    rating: 4.3,
    numReviews: 8,
    reviews: [],
  },
  {
    title: "Luxury Cashmere Hoodie",
    description: "Ultra-soft cashmere blend hoodie for ultimate comfort. Minimalist design with premium finishes.",
    price: 199.99,
    discount: 15,
    category: "hoodies",
    gender: "men",
    sizes: ["M", "L", "XL"],
    colors: ["Charcoal", "Navy", "Camel"],
    stock: 20,
    images: ["/uploads/product-3.jpg"],
    featured: true,
    rating: 4.8,
    numReviews: 20,
    reviews: [],
  },
  {
    title: "Running Performance Sneakers",
    description: "Lightweight performance sneakers with responsive cushioning. Breathable mesh upper for optimal airflow.",
    price: 159.99,
    discount: 20,
    category: "shoes",
    gender: "men",
    sizes: ["8", "9", "10", "11", "12"],
    colors: ["White/Black", "Grey/Blue"],
    stock: 45,
    images: ["/uploads/product-4.jpg"],
    featured: true,
    rating: 4.6,
    numReviews: 30,
    reviews: [],
  },
  {
    title: "Bomber Jacket - Olive",
    description: "Classic bomber jacket in premium olive nylon. Ribbed cuffs and hem with interior pocket.",
    price: 249.99,
    discount: 0,
    category: "jackets",
    gender: "men",
    sizes: ["M", "L", "XL"],
    colors: ["Olive", "Black"],
    stock: 15,
    images: ["/uploads/product-5.jpg"],
    featured: true,
    rating: 4.7,
    numReviews: 15,
    reviews: [],
  },
  {
    title: "Leather Crossbody Bag",
    description: "Handcrafted Italian leather crossbody bag. Adjustable strap with brass hardware.",
    price: 179.99,
    discount: 5,
    category: "accessories",
    gender: "unisex",
    sizes: [],
    colors: ["Brown", "Black", "Tan"],
    stock: 25,
    images: ["/uploads/product-6.jpg"],
    featured: false,
    rating: 4.4,
    numReviews: 10,
    reviews: [],
  },
  {
    title: "Floral Wrap Dress",
    description: "Elegant floral wrap dress in lightweight chiffon. Flattering silhouette with adjustable tie waist.",
    price: 139.99,
    discount: 25,
    category: "dresses",
    gender: "women",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Floral Pink", "Floral Blue"],
    stock: 30,
    images: ["/uploads/product-7.jpg"],
    featured: true,
    rating: 4.6,
    numReviews: 18,
    reviews: [],
  },
  {
    title: "High-Waist Mom Jeans",
    description: "Relaxed fit high-waist jeans with a vintage wash. Premium denim with just the right amount of stretch.",
    price: 99.99,
    discount: 0,
    category: "jeans",
    gender: "women",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Light Wash", "Medium Wash"],
    stock: 40,
    images: ["/uploads/product-8.jpg"],
    featured: false,
    rating: 4.2,
    numReviews: 22,
    reviews: [],
  },
  {
    title: "Oversized Wool Blend Coat",
    description: "Luxurious oversized coat in soft wool blend. Double-breasted design with horn buttons.",
    price: 349.99,
    discount: 10,
    category: "jackets",
    gender: "women",
    sizes: ["S", "M", "L"],
    colors: ["Camel", "Black", "Cream"],
    stock: 12,
    images: ["/uploads/product-9.jpg"],
    featured: true,
    rating: 4.9,
    numReviews: 8,
    reviews: [],
  },
  {
    title: "Silk Camisole Top",
    description: "Delicate silk camisole with adjustable spaghetti straps. Luxurious drape and feel.",
    price: 79.99,
    discount: 0,
    category: "shirts",
    gender: "women",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Champagne", "Black", "Ivory"],
    stock: 28,
    images: ["/uploads/product-10.jpg"],
    featured: false,
    rating: 4.5,
    numReviews: 14,
    reviews: [],
  },
  {
    title: "Kids Denim Overalls",
    description: "Adorable denim overalls for kids. Durable construction with adjustable straps and multiple pockets.",
    price: 49.99,
    discount: 0,
    category: "jeans",
    gender: "kids",
    sizes: ["XS", "S", "M"],
    colors: ["Blue", "Light Blue"],
    stock: 35,
    images: ["/uploads/product-11.jpg"],
    featured: false,
    rating: 4.4,
    numReviews: 16,
    reviews: [],
  },
  {
    title: "Kids Graphic Tee Pack",
    description: "Set of 3 organic cotton graphic tees for kids. Fun prints with tag-free comfort.",
    price: 39.99,
    discount: 15,
    category: "tshirts",
    gender: "kids",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Multi"],
    stock: 50,
    images: ["/uploads/product-12.jpg"],
    featured: false,
    rating: 4.3,
    numReviews: 25,
    reviews: [],
  },
  {
    title: "Ribbed Knit Sweater",
    description: "Cozy ribbed knit sweater in soft merino wool. Relaxed fit perfect for layering.",
    price: 129.99,
    discount: 0,
    category: "hoodies",
    gender: "women",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Cream", "Burgundy", "Forest Green"],
    stock: 22,
    images: ["/uploads/product-13.jpg"],
    featured: false,
    rating: 4.6,
    numReviews: 11,
    reviews: [],
  },
  {
    title: "Canvas Low-Top Sneakers",
    description: "Classic canvas sneakers with vulcanized rubber sole. Timeless style for everyday wear.",
    price: 69.99,
    discount: 0,
    category: "shoes",
    gender: "unisex",
    sizes: ["6", "7", "8", "9", "10", "11"],
    colors: ["White", "Black", "Navy", "Red"],
    stock: 60,
    images: ["/uploads/product-14.jpg"],
    featured: false,
    rating: 4.1,
    numReviews: 35,
    reviews: [],
  },
  {
    title: "Tailored Linen Pants",
    description: "Lightweight linen blend trousers with a tailored fit. Perfect for warm weather elegance.",
    price: 109.99,
    discount: 10,
    category: "pants",
    gender: "men",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Khaki", "White", "Navy"],
    stock: 30,
    images: ["/uploads/product-15.jpg"],
    featured: false,
    rating: 4.3,
    numReviews: 9,
    reviews: [],
  },
  {
    title: "Leather Belt - Italian Craft",
    description: "Handcrafted Italian leather belt with brushed silver buckle. A wardrobe essential.",
    price: 59.99,
    discount: 0,
    category: "accessories",
    gender: "men",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Brown"],
    stock: 40,
    images: ["/uploads/product-16.jpg"],
    featured: false,
    rating: 4.7,
    numReviews: 20,
    reviews: [],
  },
  {
    title: "Puffer Vest - Lightweight",
    description: "Lightweight packable puffer vest. Water-resistant shell with synthetic insulation.",
    price: 149.99,
    discount: 20,
    category: "jackets",
    gender: "unisex",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Olive", "Navy"],
    stock: 25,
    images: ["/uploads/product-17.jpg"],
    featured: false,
    rating: 4.5,
    numReviews: 13,
    reviews: [],
  },
  {
    title: "Cotton Shorts - Summer Edit",
    description: "Relaxed fit cotton shorts with side pockets. Breathable fabric for summer comfort.",
    price: 49.99,
    discount: 0,
    category: "shorts",
    gender: "men",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Khaki", "Navy", "White"],
    stock: 55,
    images: ["/uploads/product-18.jpg"],
    featured: false,
    rating: 4.2,
    numReviews: 18,
    reviews: [],
  },
  {
    title: "Velvet Evening Dress",
    description: "Stunning velvet evening dress with a plunging neckline. Floor-length design for special occasions.",
    price: 279.99,
    discount: 0,
    category: "dresses",
    gender: "women",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Emerald", "Midnight Blue", "Burgundy"],
    stock: 10,
    images: ["/uploads/product-19.jpg"],
    featured: true,
    rating: 4.9,
    numReviews: 6,
    reviews: [],
  },
  {
    title: "Polarized Sunglasses",
    description: "Premium polarized sunglasses with UV400 protection. Lightweight titanium frame.",
    price: 189.99,
    discount: 15,
    category: "accessories",
    gender: "unisex",
    sizes: [],
    colors: ["Gold/Brown", "Silver/Grey", "Matte Black"],
    stock: 30,
    images: ["/uploads/product-20.jpg"],
    featured: false,
    rating: 4.6,
    numReviews: 22,
    reviews: [],
  },
  {
    title: "Striped Long Sleeve Tee",
    description: "Classic Breton stripe long sleeve tee in soft cotton jersey. A nautical wardrobe staple.",
    price: 59.99,
    discount: 0,
    category: "tshirts",
    gender: "men",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Navy/White", "Black/White"],
    stock: 45,
    images: ["/uploads/product-21.jpg"],
    featured: false,
    rating: 4.4,
    numReviews: 15,
    reviews: [],
  },
  {
    title: "Platform Chelsea Boots",
    description: "Chunky platform Chelsea boots in smooth leather. Elastic side panels with pull tab.",
    price: 219.99,
    discount: 0,
    category: "shoes",
    gender: "women",
    sizes: ["6", "7", "8", "9", "10"],
    colors: ["Black", "Brown"],
    stock: 20,
    images: ["/uploads/product-22.jpg"],
    featured: true,
    rating: 4.7,
    numReviews: 12,
    reviews: [],
  },
  {
    title: "Cargo Jogger Pants",
    description: "Technical cargo joggers with multiple pockets. Tapered fit with elastic cuffs.",
    price: 89.99,
    discount: 10,
    category: "pants",
    gender: "men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Olive", "Grey"],
    stock: 35,
    images: ["/uploads/product-23.jpg"],
    featured: false,
    rating: 4.3,
    numReviews: 19,
    reviews: [],
  },
  {
    title: "Cropped Cardigan",
    description: "Soft cropped cardigan with mother-of-pearl buttons. Boxy fit for effortless layering.",
    price: 99.99,
    discount: 0,
    category: "hoodies",
    gender: "women",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Pink", "Lilac", "Cream"],
    stock: 18,
    images: ["/uploads/product-24.jpg"],
    featured: false,
    rating: 4.5,
    numReviews: 7,
    reviews: [],
  },
  {
    title: "Wool Fedora Hat",
    description: "Classic wool fedora with grosgrain ribbon band. Structured crown with pinched front.",
    price: 79.99,
    discount: 0,
    category: "accessories",
    gender: "unisex",
    sizes: [],
    colors: ["Charcoal", "Brown", "Black"],
    stock: 20,
    images: ["/uploads/product-25.jpg"],
    featured: false,
    rating: 4.2,
    numReviews: 11,
    reviews: [],
  },
  {
    title: "Kids Rain Boots",
    description: "Waterproof rain boots for kids with fun prints. Non-slip sole and easy pull-on design.",
    price: 34.99,
    discount: 0,
    category: "shoes",
    gender: "kids",
    sizes: ["6", "7", "8", "9", "10"],
    colors: ["Red", "Blue", "Yellow"],
    stock: 40,
    images: ["/uploads/product-26.jpg"],
    featured: false,
    rating: 4.6,
    numReviews: 28,
    reviews: [],
  },
  {
    title: "Satin Midi Skirt",
    description: "Elegant satin midi skirt with side slit. Luxurious sheen with comfortable elastic waist.",
    price: 89.99,
    discount: 10,
    category: "pants",
    gender: "women",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Champagne", "Emerald", "Navy"],
    stock: 22,
    images: ["/uploads/product-27.jpg"],
    featured: false,
    rating: 4.4,
    numReviews: 13,
    reviews: [],
  },
  {
    title: "Quilted Field Jacket",
    description: "Insulated quilted field jacket with corduroy collar. Multiple pockets for utility.",
    price: 199.99,
    discount: 0,
    category: "jackets",
    gender: "men",
    sizes: ["M", "L", "XL"],
    colors: ["Navy", "Olive", "Rust"],
    stock: 15,
    images: ["/uploads/product-28.jpg"],
    featured: false,
    rating: 4.8,
    numReviews: 10,
    reviews: [],
  },
  {
    title: "Cashmere Beanie",
    description: "Luxuriously soft cashmere beanie with ribbed fold. Lightweight warmth for cold days.",
    price: 49.99,
    discount: 0,
    category: "accessories",
    gender: "unisex",
    sizes: [],
    colors: ["Grey", "Navy", "Camel", "Black"],
    stock: 50,
    images: ["/uploads/product-29.jpg"],
    featured: false,
    rating: 4.5,
    numReviews: 24,
    reviews: [],
  },
  {
    title: "Relaxed Linen Shirt",
    description: "Breathable linen shirt with relaxed fit. Camp collar with coconut shell buttons.",
    price: 94.99,
    discount: 15,
    category: "shirts",
    gender: "men",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Sky Blue", "Sage"],
    stock: 28,
    images: ["/uploads/product-30.jpg"],
    featured: false,
    rating: 4.3,
    numReviews: 16,
    reviews: [],
  },
];

const importData = async () => {
  try {
    await Product.deleteMany();
    await User.deleteMany();

    const createdUsers = await User.insertMany(users);

    await Product.insertMany(products);

    console.log("Data Imported!");
    process.exit();
  } catch (error) {
    console.error(`${error}`);
    process.exit(1);
  }
};

const destroyData = async () => {
  try {
    await Product.deleteMany();
    await User.deleteMany();
    console.log("Data Destroyed!");
    process.exit();
  } catch (error) {
    console.error(`${error}`);
    process.exit(1);
  }
};

if (process.argv[2] === "-d") {
  destroyData();
} else {
  importData();
}
